# Generated by Django 3.1.9 on 2021-05-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='product_covers/')),
                ('call_to_action', models.CharField(choices=[('I want this', 'I want this'), ('Buy this', 'Buy this'), ('Pay', 'Pay')], max_length=20)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('content_url', models.URLField(blank=True, null=True)),
                ('content', models.FileField(blank=True, null=True, upload_to='product_files/')),
                ('price', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
