# Generated by Django 3.1.9 on 2021-05-07 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='content',
            new_name='content_file',
        ),
    ]
