# Generated by Django 3.1.9 on 2021-05-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210505_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe customer id'),
        ),
    ]
